version: "3.8"
services:
    nodeserver:
        build:
            context: ./
        ports:
            - "6000:6000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"